/*
 * Arun K
 * Jan 6 2020
 * This program calculates the numbers of the fibonacci sequence, checks numbers to verify if they are prime, and calculates the factorial of numbers
 */

/**
 *
 * @author arkir7294
 */
public class FibonacciFactorialPrime extends javax.swing.JFrame {
    int answer1;
    int fiboAnswer;
    int n = 0;
    int a = 0, b = 0, c = 1;
    int d = 0;
    int m = 0;
    int flag = 0;
    String notPrime = "Not Prime";
    String Prime = "Prime";
    
    
    
    /**
     * Creates new form FibonacciFactorialPrime
     */
    public FibonacciFactorialPrime() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Title_lbl = new javax.swing.JLabel();
        Question1_lbl = new javax.swing.JLabel();
        Answer1_txt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        Display1_lbl = new javax.swing.JLabel();
        Question2_lbl = new javax.swing.JLabel();
        Answer2_txt = new javax.swing.JTextField();
        Question2_button = new javax.swing.JButton();
        Display2_lbl = new javax.swing.JLabel();
        Question3_lbl = new javax.swing.JLabel();
        Answer3_txt = new javax.swing.JTextField();
        Question3_button = new javax.swing.JButton();
        Display3_lbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Title_lbl.setFont(new java.awt.Font("MV Boli", 1, 24)); // NOI18N
        Title_lbl.setText("--Numbers--");

        Question1_lbl.setFont(new java.awt.Font("MV Boli", 0, 20)); // NOI18N
        Question1_lbl.setText("Enter a number and click the button to find the factorial:");

        Answer1_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Answer1_txtActionPerformed(evt);
            }
        });

        jButton1.setText("Factorial");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Question2_lbl.setFont(new java.awt.Font("MV Boli", 0, 20)); // NOI18N
        Question2_lbl.setText("Enter a number and click the button to check if it is a prime number:");

        Answer2_txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Answer2_txtActionPerformed(evt);
            }
        });

        Question2_button.setText("Prime");
        Question2_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Question2_buttonActionPerformed(evt);
            }
        });

        Question3_lbl.setFont(new java.awt.Font("MV Boli", 0, 20)); // NOI18N
        Question3_lbl.setText("Enter a number and click the button to see the correspondong Fibonacci Number:");

        Question3_button.setText("Fibonacci");
        Question3_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Question3_buttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Title_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(275, 275, 275))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Answer1_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(170, 170, 170)
                        .addComponent(jButton1)
                        .addGap(175, 175, 175)
                        .addComponent(Display1_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(130, 130, 130))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Question1_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 655, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(201, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(119, 119, 119)
                .addComponent(Answer2_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(166, 166, 166)
                .addComponent(Question2_button)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Display2_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(Question3_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 810, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(121, 121, 121)
                            .addComponent(Answer3_txt, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(171, 171, 171)
                            .addComponent(Question3_button)
                            .addGap(173, 173, 173)
                            .addComponent(Display3_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Question2_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 704, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Title_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Question1_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Answer1_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jButton1)
                                .addComponent(Display1_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(40, 40, 40)
                        .addComponent(Question2_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Display2_lbl, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Answer2_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Question2_button)))
                        .addGap(38, 38, 38)
                        .addComponent(Question3_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Question3_button)
                            .addComponent(Display3_lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(84, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Answer3_txt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Answer1_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Answer1_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Answer1_txtActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        answer1 = Integer.parseInt(Answer1_txt.getText());
        
        int fact = 1;
        
        for(int i = 1;i <= answer1; i++){    
        fact=fact*i;    
  }
        Display1_lbl.setText(String.valueOf(fact));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void Answer2_txtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Answer2_txtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Answer2_txtActionPerformed

    private void Question2_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Question2_buttonActionPerformed
        n = Integer.parseInt(Answer2_txt.getText());
        
        if (n == 0 && n == 1){
            Display2_lbl.setText(notPrime);
        }else{
            for (int i = 2; i <= m;i++){
                if (n % i == 0){
                    Display2_lbl.setText(notPrime);
                    flag = 1;
                    break;
                }
            }
        if (flag == 0){
            Display2_lbl.setText(Prime);
        }
        }
        
        
    }//GEN-LAST:event_Question2_buttonActionPerformed

    private void Question3_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Question3_buttonActionPerformed
        
        
        fiboAnswer = Integer.parseInt(Answer3_txt.getText());
        
        for(int i = 1; i <= fiboAnswer; i++)
        {
            a = b;
            b = c;
            c = a + b;
            System.out.println(a + "");
            d = a;
        }
        
        Display3_lbl.setText(String.valueOf(d));
        
    }//GEN-LAST:event_Question3_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FibonacciFactorialPrime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FibonacciFactorialPrime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FibonacciFactorialPrime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FibonacciFactorialPrime.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FibonacciFactorialPrime().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Answer1_txt;
    private javax.swing.JTextField Answer2_txt;
    private javax.swing.JTextField Answer3_txt;
    private javax.swing.JLabel Display1_lbl;
    private javax.swing.JLabel Display2_lbl;
    private javax.swing.JLabel Display3_lbl;
    private javax.swing.JLabel Question1_lbl;
    private javax.swing.JButton Question2_button;
    private javax.swing.JLabel Question2_lbl;
    private javax.swing.JButton Question3_button;
    private javax.swing.JLabel Question3_lbl;
    private javax.swing.JLabel Title_lbl;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
